version: '2.2'

networks:
  kong-edu-net:
    name: kong-edu-net
    driver: bridge

services:
 
# BanKonG
  bankong-frontend:
   networks:
   - kong-edu-net
   image: svenwal/bankong-frontend:latest
   container_name: bankong-frontend
   hostname: frontend.bankong
   restart: on-failure
   ports:
    - 29080:8080
  bankong-backend-transactions:
   networks:
   - kong-edu-net
   image: svenwal/bankong-backend-transactions:latest
   container_name: bankong-backend-transactions
   hostname: backend-transactions.bankong
   restart: on-failure
   ports:
    - 3000:3000
   environment:
     BACKEND_REGION: your home
     BACKEND_DATACENTER: local laptop
     BACKEND_ARCHITECTURE: docker-compose
  bankong-backend-orders:
   networks:
   - kong-edu-net
   image: svenwal/bankong-backend-orders:latest
   container_name: bankong-backend-orders
   hostname: backend-orders.bankong
   restart: on-failure
